[package]
name = "awari-compositor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smithay-client-toolkit = "0.19"
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
